### ISSUE TITLE
文件夹无法设置描述，报错'str' object has no attribute 'keys'

### ISSUE THREAD

**Issue by Huricy-Miun** [zaxtyson/LanZouCloud-API#67]
就这一行出错
lzy.set_desc(4381456, '文件夹描述', is_file=False)
具体情况
  File "D:\Apps\Python\lib\site-packages\lanzou\api\core.py", line 581, in get_share_info
    if ('f_id' in f_info.keys() and f_info['f_id'] == 'i') or ('name' in f_info.keys() and not f_info['name']):
AttributeError: 'str' object has no attribute 'keys'
不管文件夹本来有没有描述都会返回这个错误

**Comment by zaxtyson** [comment]
测试了很多次, 似乎复现不了

**Comment by Aislend** [comment]
> 

啊这，是只能自己手动设置了的意思吗……好在也没啥工作量，作者大大辛苦了

**Comment by zaxtyson** [comment]
我自己的文件夹都可以设置描述, 不知道你这个是什么神奇的情况, 如果可以的话, 能邮件发给我一下cookie吗, 我登陆你的号去排查问题

**Comment by Aislend** [comment]
谢谢大佬！我的cookie：


cookie = {'ylogin': '1586545', 'phpdisk_info': 'BTAHMARuVmwHMFQwDWIAUwZiV1wPZ1U7VG8FYAA0CjADMgUwVTVWbQ4%2BAVgKZQNsVWYAMg0yXWwDNwQ2AjUDYwUzBzIEYVZtBzFUMA1hAGwGYlcxDzRVYFRgBW0AMwpqAz8FNlViVm4ONQFlClkDaFU8ADoNYV04AzgEYQIzAzMFNgc3'}


夜深了要不早点休息（）





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zaxtyson/LanZouCloud-API"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月11日(星期六) 凌晨1:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zaxtyson/LanZouCloud-API] 文件夹无法设置描述，报错'str' object has no attribute 'keys' (Issue #67)





 
我自己的文件夹都可以设置描述, 不知道你这个是什么神奇的情况, 如果可以的话, 能邮件发给我一下cookie吗, 我登陆你的号去排查问题
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Aislend** [comment]
> 我自己的文件夹都可以设置描述, 不知道你这个是什么神奇的情况, 如果可以的话, 能邮件发给我一下cookie吗, 我登陆你的号去排查问题

已经发了，不知道您收到没
